MDScreen:
    name:"food"
    MDFloatLayout:
        md_bg_color: (33/255, 150/255, 243/255, 1)
        MDTextField:
            id: food_input
            hint_text: "Food"
            pos_hint: {"center_x": .5, "center_y": .7}
            size_hint_x: .8
            mode: "round"
        MDTextField:
            id: calories_input
            hint_text: "Calories"
            pos_hint: {"center_x": .5, "center_y": .5}
            size_hint_x: .8
            mode: "round"